name: Security Scan

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - master
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: "0 0 * * 1"

jobs:
  trivy-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get commit SHA
        id: commit
        run: |
          echo "build-date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=$(cat ${GITHUB_WORKSPACE}/VERSION)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container for scanning
        uses: docker/build-push-action@v6
        env:
          COMMIT_BUILD_DATE: ${{ steps.commit.outputs.build-date }}
          COMMIT_SHA: ${{ steps.commit.outputs.sha }}
          COMMIT_VERSION: ${{ steps.commit.outputs.version }}
          DEST_IMAGE: omni-api-scan-image-${{ env.COMMIT_SHA }}.tar
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: false
          tags: omni-api:scan
          outputs: type=local,dest=./${{ env.DEST_IMAGE }}
          labels: |
            org.opencontainers.image.title="Omni API"
            org.opencontainers.image.description="A REST API to interface with Sidero Omni"
            org.opencontainers.image.version=${{ env.COMMIT_VERSION }}
            org.opencontainers.image.created=${{ env.COMMIT_BUILD_DATE }}
            org.opencontainers.image.revision=${{ env.COMMIT_SHA }}
            org.opencontainers.image.source=https://github.com/Jubblin/omni-api
            org.opencontainers.image.licenses="MIT"
          build-args: |
            BUILD_DATE=${{ env.COMMIT_BUILD_DATE }}
            SHA=${{ env.COMMIT_SHA }}
            VERSION=${{ env.COMMIT_VERSION }}

      # - name: Load image
      #   if: github.event_name != 'pull_request'
      #   run: |
      #     docker load -i /tmp/${{ matrix.arch }}${{ matrix.image-suffix }}-image.tar
      #     docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.arch }}${{ matrix.image-suffix }}-local ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.arch }}${{ matrix.image-suffix }}-scan

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: omni-api:scan
          format: "sarif"
          exit-code: "0"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
